# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jOWMy0ZhGHdEmlqgoFODI7TesiGAzWuH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression

path='/content/drive/MyDrive/csv files/Iris.csv'
data=pd.read_csv(path)
data.head()

data.describe()

data.info()

data["Species"].value_counts()

sns.FacetGrid(data,hue="Species",height=5).map(plt.scatter,"SepalLengthCm","PetalLengthCm").add_legend()

x=data[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]].values
y=data[["Species"]].values

model=LogisticRegression()
model.fit(x,y)

model.score(x,y).round(2)

Actual=y
predicted=model.predict(x)

from sklearn import metrics
print(metrics.classification_report(Actual,predicted))

print(metrics.confusion_matrix(Actual,predicted))

predicted=model.predict([[5.1,3.5,1.4,0.2]])
predicted



